### ISSUE TITLE
Using NotifyOnTargetUpdated=True causes StackOverflow Exception

### ISSUE THREAD

**Issue by Raziel233** [tom-englert/DataGridExtensions#10]
Trying to build a filter component with a combobox with distinct values but when adding NotifyOnTargetUpdated=True I get a StackOverflow Exception.

` <ComboBox ItemsSource="{Binding SourceValues, RelativeSource={RelativeSource Mode=FindAncestor, AncestorType=dgx:DataGridFilterColumnControl}, Mode=OneWay, UpdateSourceTrigger=PropertyChanged, NotifyOnTargetUpdated=True}"/>`

**Comment by tom-englert** [comment]
In the [sample application](https://github.com/tom-englert/DataGridExtensions/blob/master/DataGridExtensionsSample/MainWindow.xaml#L35) adding it works fine:
```xml
    <ControlTemplate x:Key="ComboboxFilter">
      <Grid d:DataContext="{d:DesignInstance dgx:DataGridFilterColumnControl}">
        <Grid>
          <Control Style="{DynamicResource {x:Static dgx:DataGridFilter.IconStyleKey}}"/>
          <ComboBox x:Name="ComboBox" Text="{Binding Path=Filter, UpdateSourceTrigger=PropertyChanged, NotifyOnTargetUpdated=True}" ItemsSource="{Binding SelectableValues}" IsEditable="True" />
        </Grid>
      </Grid>
```
Can you provide a sample where it fails?

**Comment by Raziel233** [comment]
NotifyOnTargetUpdated=True should be on the ItemSource binding, not Text binding right? Sample application crashes aswell then.

**Comment by tom-englert** [comment]
But what would be the use case of this? Where do you hook into the TargetUpdated even?

**Comment by Raziel233** [comment]
Ahh, my mistake, I thought it was the combobox:s itemsource who needed the NotifyOnTargetUpdated but it was the datagrid... Sorry! It works now.

**Comment by tom-englert** [comment]
😄
