### ISSUE TITLE
Filtering event is not raised when clearing the filter on a column

### ISSUE THREAD

**Issue by Nu-ke** [tom-englert/DataGridExtensions#11]
When clearing a filter (ex: click on the cross or remove all filter text) the Filtering event is not raised. It is useful to raise it !:) (L291 DataGridFilterHost.cs)

**Comment by tom-englert** [comment]
The Filtering event only notifies about additional columns, so it does not apply here.
The FilterChanged event will be raised always, so probably that is what you should use:[DataGridFilterHost.cs#L305](https://github.com/tom-englert/DataGridExtensions/blob/master/DataGridExtensions/DataGridFilterHost.cs#L305)

**Comment by Nu-ke** [comment]
I have seen this event, but it is actually raised before the filter is applied to the collection : https://github.com/tom-englert/DataGridExtensions/blob/d43942ddf476927725e616fe11934975409f8016/DataGridExtensions/DataGridFilterHost.cs#L310
In my case, my datagrid is filtered not only with the text in the column but also by other criterias, outside the datagrid. I was using the Filtering event with Cancel = true to handle this complex filter :
https://github.com/tom-englert/DataGridExtensions/blob/d43942ddf476927725e616fe11934975409f8016/DataGridExtensions/DataGridFilterHost.cs#L296-L299
As far as I've seen, there is currentlty no way prevent the clear of a filter to remove all existing filter in the datagrid. 
Maybe can you add an event after the collectionview.Filter is set (L310) so that the control can go back to the caller?

**Comment by tom-englert** [comment]
I'm not really sure if I understood what you want to achieve. Maybe you should rather use custom column filters instead of using the defaults and then trying to override the behavior?

**Comment by tom-englert** [comment]
@Nu-ke did you solve this by your own already?

**Comment by Nu-ke** [comment]
No, I haven't solved it yet in a clean way. The IContentFilter.IsMatch method is not called when all filter are cleared in the datagrid. 
I think it is a shame that there is no way to know when the user clear all filter of a datagrid.

**Comment by tom-englert** [comment]
Again: I don't see the use case that you want to achieve. 
Why should the IsMatch method being called when there is nothing to math because the filter condition is cleared?
Please post some sample code to show what you are trying to achieve.

**Comment by tom-englert** [comment]
@Nu-ke any input on this?

**Comment by Nu-ke** [comment]
I have solved this using an External filter and a hack with the Filtered event.
Thanks
