### ISSUE TITLE
Filter Binding Example

### ISSUE THREAD

**Issue by sethreno** [tom-englert/DataGridExtensions#13]
Can anyone provide an example showing how to bind the value of a filter control to a property on the view model? I'm trying to set default values for the filter.

**Comment by tom-englert** [comment]
see https://github.com/tom-englert/DataGridExtensions/commit/944d8e81c09340268de16293caf2d6366e793f73

You could also use one of the approaches found here:
https://stackoverflow.com/questions/22073740/binding-visibility-for-datagridcolumn-in-wpf

**Comment by sethreno** [comment]
@tom-englert  This was really helpful . Thank you!
