### ISSUE TITLE
Filtering DataGridTextColumn with Converter in Binding

### ISSUE THREAD

**Issue by lstauber** [tom-englert/DataGridExtensions#14]
What is the simplest way to filter the converted value? Haven't found anything in the samples, could you please include one such column?
Thanks, Ludek.

**Comment by tom-englert** [comment]
That's hardly possible.
The [SortMemberPath](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.datagridcolumn.sortmemberpath) is just a string - which means you can't sort by a converted binding value, and doing filtering by a different criteria than sorting would be very confusing.
It's much easier to use a design that does not require a converter.
