### ISSUE TITLE
Visible Items

### ISSUE THREAD

**Issue by Symbai** [tom-englert/DataGridExtensions#17]
Would be nice to be able to get all visible items as there is no good way to achieve that by default.

**Comment by tom-englert** [comment]
I assume you refer to the filtering. What about `DataGrid.Items`?

**Comment by Symbai** [comment]
No I meant to get all items which are visible on the screen. Imagine the itemsource has 400 items and the user scrolled to item #300 and the window shows 16 items than #300 up to #316 are visible. But if the user resizes the window to fullscreen, item #300 up to #350 are visible.

DataGrid.Items will instead return all items in the current view (which includes items that may not visible to the user)

**Comment by tom-englert** [comment]
You would have to walk the visual tree and check the position of each row or column to achieve this.
However this is such an unusual use case, I doubt this should make it into DGX.
