### ISSUE TITLE
DataGrid in TabControl - Values in TextBoxes lost after tab change

### ISSUE THREAD

**Issue by PorkyMcPork** [tom-englert/DataGridExtensions#18]
Hi,

I got a small issue when the filtered DataGrid is put inside a TabItem like in the sample project. When I use a filter with TextBox input (e.g. the IntegerGreatherThanFilterControl) and I switch to another tab and back, the input value is no longer displayed. The filter itself is still active, just the input value is no longer visible.
I think this is due to the fact that the TabControl is drawing all the visuals inside a TabItem on demand and doesn't keep them loaded.

Is there a way to keep the input values in the TextBox after tab switches?

**Comment by tom-englert** [comment]
I have fixed the sample, see latest commit.
