### ISSUE TITLE
MultipleChoiceFilter does not match on Enums

### ISSUE THREAD

**Issue by Brains** [tom-englert/DataGridExtensions#19]
Selecting an item in popup `ListBox` does not filter rows in `DataGrid` when underlying type is not `string` but:
```cs
public enum Permission
{
    None,
    Read,
    Write,
}
```
To fix that I've changed
https://github.com/tom-englert/DataGridExtensions/blob/480d15443db131a28398c60f73195f52ef94c97f/DataGridExtensionsSample/MultipleChoiceFilter.xaml.cs#L118-L121
to
```cs
return ExcludedItems?.Contains(value?.ToString()) != true;
```
Then it started to filter rows with `enum` values

Not sure, it's completely valid fix, just wanted to share, might be useful.

**Comment by Brains** [comment]
Also, next column with simple `ComboBoxFilter` worked with `Enum` out-of-box
https://github.com/tom-englert/DataGridExtensions/blob/480d15443db131a28398c60f73195f52ef94c97f/DataGridExtensionsSample/MainWindow.xaml#L208-L211

**Comment by tom-englert** [comment]
Updated sample
