### ISSUE TITLE
Coherence between 2 MultipleChoiceFilter

### ISSUE THREAD

**Issue by moh-a-med** [tom-englert/DataGridExtensions#2]
Hello,

I notice a problem when using your excellent library.

When two MultipleChoiceFilter are proposed in a datagrid, the selection of some elements in the first one will modify the results in the datagrid but it has no effect on the values proposed in the second MultipleChoiceFilter. 

Can that be done ?

**Comment by tom-englert** [comment]
You can bind to `DataGridFilterColumnControl.Values` instead of `DataGridFilterColumnControl.SourceValues`, that should give you the distinct list of all currently visible items in that column.

**Comment by tom-englert** [comment]
Added an additional `DataGridFilterColumnControl.SelectableValues` property that holds all values that are currently selectable in the column.
