### ISSUE TITLE
.NET Core 3.0 Support

### ISSUE THREAD

**Issue by mjuen** [tom-englert/DataGridExtensions#21]
Are there any plans to support .NET Core 3.0?

**Comment by tom-englert** [comment]
shouldn't that work already?

**Comment by mjuen** [comment]
If I see that correctly you only target .NET 4.0 Client and .NET 4.5.

https://github.com/tom-englert/DataGridExtensions/blob/480d15443db131a28398c60f73195f52ef94c97f/DataGridExtensions/DataGridExtensions.csproj#L6

**Comment by tom-englert** [comment]
Yep, that should work fine with coreapp3.0 desktop

**Comment by tom-englert** [comment]
https://devblogs.microsoft.com/dotnet/net-core-3-and-support-for-windows-desktop-applications/
Using .NET Core 3 for an Existing Desktop Application

For new desktop applications, we’ll guide everyone to start with .NET Core 3. The more interesting question is what the experience will be like to move existing applications, particularly big ones, to .NET Core 3. We want the experience to be straightforward enough that moving to .NET Core 3 is an easy choice for you, for any application that is in active development. Applications that are not getting much investment and don’t require much change should stay on .NET Framework 4.8.

Quick explanation of our plan:

-    Desktop applications will need to target .NET Core 3 and recompile.
-    Project files will need to be updated to target .NET Core 3.
-    **Dependencies will not need to retarget and recompile. There will be additional benefits if you update dependencies.**

**Comment by tom-englert** [comment]
However feel free to provide a PR if you think there are benefits.
