### ISSUE TITLE
Column virtualization is not supported

### ISSUE THREAD

**Issue by farnyser** [tom-englert/DataGridExtensions#23]
DataGrid **loops** between empty/full when I apply a filter that match no row.

To trigger the bug some options are set:  
- can user add row = false 
- column virtualization = true

It seems that the column filtered has to be not visible unless you scroll horizontally (last right column)

![image](https://user-images.githubusercontent.com/1619518/63863475-9c94ca00-c9ae-11e9-92db-5e9234af9a04.png)

![image](https://user-images.githubusercontent.com/1619518/63863524-a9b1b900-c9ae-11e9-8851-550e428a8c3d.png)

Sample project : 
[BugDataGrid.zip](https://github.com/tom-englert/DataGridExtensions/files/3551331/BugDataGrid.zip)

(If you put column virtualization = false, then the bug disappear, but the column filtered is on the far right and the scrollbar is not visible anymore => you can't remove the filter)

**Comment by tom-englert** [comment]
This was never meant to work with column virtualization. 
In this case the filter can't be attached to the column any longer. 
If you have an idea how to solve this, you may provide a PR that can fix it.

For the latter case you can click on the top-left select all button in the grid, that will clear all filters.
