### ISSUE TITLE
Popup filter with custom template and default filtering

### ISSUE THREAD

**Issue by bgolemba** [tom-englert/DataGridExtensions#24]
Is there simple way to create popup filter which will be acting as a default filter (aka column contains)?
I don't want to change default filter behavior just its design.

**Comment by tom-englert** [comment]
Just provide your own template like in the samples

**Comment by bgolemba** [comment]
But when I did this the filter behavior stops to working.

**Comment by bgolemba** [comment]
I figured it out. Just binding to property Filter :)
