### ISSUE TITLE
Missing resources in netcoreapp3.0 target

### ISSUE THREAD

**Issue by ltrzesniewski** [tom-englert/DataGridExtensions#25]
The Generic.xaml resources aren't included in the netcoreapp3.0 version, and therefore the library doesn't work on that target. Copying these to my app makes everything work properly again.

See the difference bewteen net45 and netcoreapp3.0 versions:

![image](https://user-images.githubusercontent.com/7913492/65680950-491ea600-e058-11e9-9f42-0accfae578a8.png)

**Comment by tom-englert** [comment]
Thanks for pointing this out! 
Can you try 2.0.1? that should fix it.

**Comment by ltrzesniewski** [comment]
Thanks! v2.0.1 works fine.
