### ISSUE TITLE
Microsoft.Xaml.Behaviors.Wpf 1.0.30 - broken dependency

### ISSUE THREAD

**Issue by LordPinhead** [tom-englert/DataGridExtensions#26]
Hi Tom,

thanks for the library, it worked great so far.
The new WPF Behaviors library, Microsoft release 2 days ago, does not work with the Extension library.

VS is just complaining that a dependency was not met and is closing the application after that.

So reproducing is easy, just update it.

**Comment by tom-englert** [comment]
Updated behaviors to 1.1.3
