### ISSUE TITLE
DataGridFilterColumnControl.SourceValues to be updated on DataGrid.ItemsSource CollectionChanged

### ISSUE THREAD

**Issue by Avrohom** [tom-englert/DataGridExtensions#27]
Hi and thanks for this great project.

After experimenting a bit with this library, I figured out that the `SourceValues `of the `DataGridFilterColumnControl `class is not being updated when items in the `DataGrid `are being added or deleted (ie, that's when the underlying `ItemsSource.CollectionChanged`).

Would also be nice if `SourceValues `could be updated not only on the  `dataGrid.RowEditEnding` event, but anytime the underlying data gets changed outside cell editing.

**Comment by Avrohom** [comment]
Hi @tom-englert !

Great work! Tested and it works.

How about cell changes from outside cell / row editing? Such as editing that occurs in a detail view / control?

**Comment by tom-englert** [comment]
That would be not so easy - you would need to listen to all property changed events of all items...
The only way to handle this without impacting everyone else would be to expose a method on the `DataGridFilterHost` that would allow you to trigger the change notification of the `SourceValues`.

**Comment by Avrohom** [comment]
And how would I get to the `DataGridFilterHost` from a `ViewModel`? 

I would need a reference to the `DataGrid` inside the `ViewModel`. If so, I could trigger a `RowEditEnding `on the `DataGrid` such as `dataGrid.CommitEdit(DataGridEditingUnit.Row, true)`.

If the above works than we have no need to add anything to the `DataGridFilterHost`. Am I wrong?

**Comment by tom-englert** [comment]
You can access the host from the `DataGrid`: https://github.com/tom-englert/DataGridExtensions/blob/a43bddaeb08717191a47031f090906c6d14dac02/DataGridExtensions/DataGridFilter.cs#L54

**Comment by Avrohom** [comment]
I have tried with CommitEdit. Initially didn't work, so I inserted a call to BeginEdit first, and that did the trick. Now everything works fine.
