### ISSUE TITLE
添加 xmlns:dgx="urn:tom-englert.de/DataGridExtensions"，无法解析资源

### ISSUE THREAD

**Issue by caoyuanfeng** [tom-englert/DataGridExtensions#28]
在页面中添加添加 xmlns:dgx="urn:tom-englert.de/DataGridExtensions"后，使用到的
Style="{DynamicResource ResourceKey={x:Static Member=res:CustomResourceDictionary.ButtonDefaultStyle}}"提示无法解析资源，是有冲突吗？

**Comment by tom-englert** [comment]
Sorry, I don't speak Chinese
