### ISSUE TITLE
ComboBoxColumn not filterable

### ISSUE THREAD

**Issue by TeaJAge** [tom-englert/DataGridExtensions#29]
Is it possible to create a filter for this by default?

**Comment by tom-englert** [comment]
You must set the SortDescription for non-text columns

**Comment by jogibear9988** [comment]
??? 
SortDescription for Filtering??

Can't you use ItemsSource of ComboBoxColumn?

**Comment by tom-englert** [comment]
Sorry, its [SortMemberPath](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.datagridcolumn.sortmemberpath)

**Comment by jogibear9988** [comment]
I've created a pull req for this: https://github.com/tom-englert/DataGridExtensions/pull/30

**Comment by jogibear9988** [comment]
![image](https://user-images.githubusercontent.com/364896/69636976-08430d80-1058-11ea-9f02-b5c5b09870dc.png)

**Comment by jogibear9988** [comment]
![image](https://user-images.githubusercontent.com/364896/69638555-35dd8600-105b-11ea-8af6-c197918421ed.png)

**Comment by jogibear9988** [comment]
@tom-englert 
is this pull okay?

**Comment by TeaJAge** [comment]
@tom-englert 
can you merge it?

**Comment by tom-englert** [comment]
@TeaJAge sorry, had no time yet to review. 
I don't see the common usecase for this; 
this looks very special, with an individual design that does not fit the other controls.
I don't think this is something that should make it into the standard. 
Maybe as a sample in the sample app?

**Comment by jogibear9988** [comment]
Why is it special? When a ComboBoc Column is used, you use itemssource to Provide the data...

**Comment by jogibear9988** [comment]
Are Enum Columns so special?

**Comment by jogibear9988** [comment]
Why is the Design individual, I did like you do it on the checkbox columns. Should I show the Filter Button?
At the moment "Enum" Columns are not yet filterable

**Comment by tom-englert** [comment]
As you can see in the sample there are already two combobox columns, both with totally different filter controls. Your's is just anoter one, with less functionality (e.g. only single selection of the filtered value), so why do you think this should be the default? Why not this:
![image](https://user-images.githubusercontent.com/10229954/70028354-babd2800-15a4-11ea-8575-7e9dd9ccb0d2.png)

**Comment by jogibear9988** [comment]
@tom-englert 
i did not see that. but why is your's not used as a default when I auto generate columns?

I don't want mine as default, I want one as default that ComboBox works out of the box

**Comment by jogibear9988** [comment]
But I'd like your second one without the list more. Cause on Big Collections the other one could get huge

**Comment by jogibear9988** [comment]
We use Autogenerated Columns, so it would be nice if enums work out of the box, same like the rest

**Comment by tom-englert** [comment]
> But I'd like your second one with the normal combobox more. Cause on Big Collections the other one could get huge

So you see there is not that one default that fits eveybody - there are so many constraints to consider.

Just add the control template to your app.xaml, then it works for you. You don't need to change the default for the ROW.

**Comment by tom-englert** [comment]
Also if you have plain enums with auto-generated columns, how would you localize the values?

**Comment by jogibear9988** [comment]
Localization is not required on this project. 
How can I do it with auto generated columns?
Maybe an extra Dependency Property, AutoGenerateCoboboxFilter if you'd not like it in default?

**Comment by tom-englert** [comment]
> Localization is not required on this project.
So you see this is project specific
> How can I do it with auto generated columns?
What exactly are you referring to here?
> Maybe an extra Dependency Property, AutoGenerateCoboboxFilter if you'd not like it in default?
What about using this as default just in your project? Why must this be implemented here?

**Comment by jogibear9988** [comment]
@tom-englert 
Localization is not required on this project.
So you see this is project specific
Yes, but as a Default, the Enum Values are not Localized in the Grid, why should they in the ComboBox?

yes, but how can I implement it without copying most of your code?

I can fork your repo and do it myself, but I would avoid this if possible... 

How can I do it with auto generated columns?
How can I use your Extension with ComboBoxColumns when I only use AutoGenerated Columns For my Types. I do not generate any ColumnDefinition in XAML.

**Comment by tom-englert** [comment]
You just move the template that you added to the generic.xaml to your app.xaml - that should do the job

**Comment by tom-englert** [comment]
> Yes, but as a Default, the Enum Values are not Localized in the Grid, why should they in the ComboBox?

That's why this is not a practical use case, since they are not localized in the grid.

**Comment by jogibear9988** [comment]
?? don't understand why it's not practical use case.
Think many people have a Grid with enums and like to filter them...

**Comment by jogibear9988** [comment]
You can close the issue

**Comment by jogibear9988** [comment]
maybe you could include the ComponentResourceKey for the ComboBoxColumn in your Code?
   public static readonly ResourceKey ComboBoxColumnFilterTemplateKey = new ComponentResourceKey(typeof(DataGridFilter), typeof(DataGridComboBoxColumn));

**Comment by tom-englert** [comment]
@jogibear9988 that's reasonable, added it, defaults to the standard text filter.
