### ISSUE TITLE
DOTNET 4.6.2

### ISSUE THREAD

**Issue by nat2k5us** [tom-englert/DataGridExtensions#3]
Does not work with DOTNET 4.6.2 - I will try download the code and rebuild with 4.6.2.

The Syste.Windows.Interactivity is the incompatible dll

**Comment by tom-englert** [comment]
maybe you have just to add a binding redirect into you app.config?

**Comment by tom-englert** [comment]
@nat2k5us did it work out?

**Comment by nat2k5us** [comment]
Yes.
I did not have to recompile the library with 4.6.2 
1. Added the nuget package - saw the System.Windows.Interactivity was not needed this time. 
2.  added  xmlns:dgx="urn:tom-englert.de/DataGridExtensions"
3.  added dgx:DataGridFilter.IsAutoFilterEnabled="True"
