### ISSUE TITLE
MahApp style integration

### ISSUE THREAD

**Issue by tgiachi** [tom-englert/DataGridExtensions#31]
Hi!
Is possible integrate current mahApps style with your datagrid extension?

![image](https://user-images.githubusercontent.com/942730/70218044-8ed7a900-1742-11ea-8216-c87d07463fbe.png)

Thank you!

**Comment by tom-englert** [comment]
Seems to be an issue with the mapApps style, works great with [TomsToolbox.WpfStyles](https://github.com/tom-englert/TomsToolbox/tree/master/TomsToolbox.Wpf.Styles):

![image](https://user-images.githubusercontent.com/10229954/70267229-4c43ba00-179e-11ea-8626-e0148e89f9cc.png)

**Comment by Brains** [comment]
Possible for sure. 
![image](https://user-images.githubusercontent.com/5301844/70449607-f0817580-1aaa-11ea-8cbc-08531a5f89eb.png)

I've found this in my `.xaml`
```xaml
<!-- Needed for DataGridFilter -->
<Style TargetType="{x:Type DataGridColumnHeader}"
       BasedOn="{StaticResource MetroDataGridColumnHeader}" />
```

**Comment by tom-englert** [comment]
Sure, if you use another style system, you need to override all default styles.

**Comment by tom-englert** [comment]
@Fruchtzwerg94 DGX did not change in this aspect, maybe MahApp changed?

**Comment by Fruchtzwerg94** [comment]
Indeed, after playing around a little bit I was able to get it running again by placing the following snippet in the **parent control of the DataGrid**:

```
<!-- Needed for DataGridFilter -->
<StackPanel.Resources>
    <ResourceDictionary>
        <ResourceDictionary.MergedDictionaries>
            <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.DataGrid.xaml" />
        </ResourceDictionary.MergedDictionaries>
        <Style TargetType="{x:Type DataGridColumnHeader}"
               BasedOn="{StaticResource MahApps.Styles.DataGridColumnHeader}" />
    </ResourceDictionary>
</StackPanel.Resources>
```
