### ISSUE TITLE
DataGridFilter.SetIsAutoFilterEnabled

### ISSUE THREAD

**Issue by cahalu** [tom-englert/DataGridExtensions#33]
Using **DataGridExtensions.DataGridFilter.SetIsAutoFilterEnabled(MyDataGrid, MyBool);** will not make any visual change.

**Comment by tom-englert** [comment]
Maybe just try to use it like in the sample app?

**Comment by tom-englert** [comment]
If you don't tell me what you are trying to do, I can't help you
