### ISSUE TITLE
Regression (v2.4): DataGridFilterColumn doesn't work for combobox column

### ISSUE THREAD

**Issue by WaterDesk** [tom-englert/DataGridExtensions#35]
Run DataGrid Extensions Sample app, go to the `Extend 2` tab, the filter of Text/Custom column is not expected as v2.3
![image](https://user-images.githubusercontent.com/34054635/89023513-46669e80-d356-11ea-913b-d6a9ee43a33b.png)

**Comment by WaterDesk** [comment]
thanks for the quick fix

**Comment by Brains** [comment]
Thanks as well
