### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by marcosgerene** [tom-englert/DataGridExtensions#37]
Hey there,

First one, congratulations about the project, it's amazing!

I have a few questions about the usability:

1. Can I use the filter only in only a specific column? If so, how do I do it?

2. Can I use a range to the search? If so, how do I do it?

Thank you!

**Comment by tom-englert** [comment]
See here in the sample app:

![image](https://user-images.githubusercontent.com/10229954/89528749-dcce1080-d7eb-11ea-8c19-cd1f16d69c5b.png)

**Comment by marcosgerene** [comment]
@tom-englert, thanks you for answer.

I can't compile the sample app, if you can, please send me a code-example (just for the 1st question).

Anyway, I will try compile that again.

Thanks you so much =D
