### ISSUE TITLE
Method not supported

### ISSUE THREAD

**Issue by ShemJM** [tom-englert/DataGridExtensions#38]
I added this nuget to my WPF project and enabled AutoFilter on one of my DataGrids.  When I typed into the filter boxes an exception was thrown which took me to Line 277 of the DataGridFileHost class. The error message said 'Specified method is not supported.'

My app targets .NET Framework 4.7.2. Is that supported?

**Comment by tom-englert** [comment]
Yes, anything beyond 4.5 should work...

**Comment by ShemJM** [comment]
@tom-englert Could the problem that the ItemSource of my DataGrid is `someDataTable.DefaultView`

**Comment by tom-englert** [comment]
That sounds reasonable, maybe this table implementation is incomplete

**Comment by ShemJM** [comment]
Yeah that seems to have been the problem. I'll close this.
