### ISSUE TITLE
Filtering does not support CollectionViewSource

### ISSUE THREAD

**Issue by fredgelinas** [tom-englert/DataGridExtensions#39]
Setting the DataGrid's AutoGenerateColumns to True and ItemsSource to a CollectionViewSource, the filtering raises an unhandled exception: System.NotSupportedException: 'Specified method is not supported.'

I'd like to use the filtering feature and my data is loaded in a DataTable. Columns are unknown at design time and may change on user's input.  A workaround would also be welcomed.

namespace TestGrid
{
  public partial class MainWindow : Window
  {
    public MainWindow()
    {
      InitializeComponent();
      //Doesn't work
      //dataGrid.ItemsSource = GetData().DefaultView; 

      //Doesn't work
      CollectionViewSource mycollection = new CollectionViewSource();
      mycollection.Source = GetDataTableData();
      dataGrid.ItemsSource = mycollection.View;

    }

    public DataTable GetDataTableData()
    {
      DataTable qData = new DataTable();
      qData.Columns.Add("Name", typeof(String));
      qData.Columns.Add("Age", typeof(int));
      DataRow dr = qData.NewRow();
      dr["Name"] = "Bob";
      dr["Age"] = 98;
      qData.Rows.Add(dr);     
      return qData;
    }   
  }
}

**Comment by Insire** [comment]
#38 seems relevant, as there seems to be no support for datatables at the moment

**Comment by tom-englert** [comment]
It's the other way round - default view returned by `CollectionViewSource` for a `DataTable` does not support filtering. (https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.icollectionview.canfilter, https://referencesource.microsoft.com/#PresentationFramework/src/Framework/System/Windows/Data/BindingListCollectionView.cs,293)
Not all collection views support filtering, e.g. the `BindingListCollectionView` returned as default view for a `DataTable ` source does not.
You have to write your own adapter and explicitly create a `ListCollectionView` instead

**Comment by fredgelinas** [comment]
Thank you.
Workaround that seems to work:
dataGrid.ItemsSource = new ListCollectionView(GetDataTableData().DefaultView);
