### ISSUE TITLE
Not able to use this with System.Window.Interactivity for .NET 4.5 Frame work

### ISSUE THREAD

**Issue by LakshayKhosla** [tom-englert/DataGridExtensions#6]
It throws DeferrableContent Exception with 3.0.40218.0 System.Window.Interactivity.dll i.e. for .NET framework 4.5.
But when used with 2.0.20525.0 System.Window.Interactity

**Comment by LakshayKhosla** [comment]
Continuation - System.Window.Interactivity.dll worked fine.
Can you please add a support for.NET 4.5?

**Comment by tom-englert** [comment]
What's the benefit of using 3.0.40218.0 over  2.0.20525.0? Are there any new features?

**Comment by LakshayKhosla** [comment]
Probably yes.
I was using this with MahApps.Metro, MahApps.Metro 4.5 uses System.Windows.Interactivity 3.0.40218.0 for the controls. So it is giving me the error to use v2 instead of v3. But due to some internal code I am not able to change framework to 4.0 of my application. So can you build this for 4.5 Framework?

**Comment by tom-englert** [comment]
And a binding redirect does not help?

**Comment by LakshayKhosla** [comment]
No. It doesn't help

**Comment by tom-englert** [comment]
How did you set it up?

**Comment by LakshayKhosla** [comment]
I tried it with Codebase and Assembly Binding Redirect, but still it throws the same error. I included both the versions of System.Windows.Interactivity but it doesn't seemed to work

**Comment by tom-englert** [comment]
It should look something like this:
```
<dependentAssembly>
          <assemblyIdentity name="System.Windows.Interactivity" publicKeyToken="31bf3856ad364e35" culture="neutral"/>
          <bindingRedirect oldVersion="4.0.0.0" newVersion="4.5.0.0"/>
</dependentAssembly>```

**Comment by tom-englert** [comment]
@LakshayKhosla did that solve your problem?

**Comment by LakshayKhosla** [comment]
Yes.
It worked!
Thanks
Closing the issue
