### ISSUE TITLE
Scrolling in DataGrid with arrow up ends in the title filter editor

### ISSUE THREAD

**Issue by lstauber** [tom-englert/DataGridExtensions#8]
Scrolling in DataGrid with arrow up ends in the title filter editor (in column header) instead in the first line of data. And it even does not allow to jump back into data rows using arrow down.

Please disable this scroll to column header (better) or at least allow going back to data row area using array down (worse, but still acceptable).

**Comment by tom-englert** [comment]
Focus handing is done by the `System.Windows.Input.KeyboardNavigation` class, not by DGX.
You can configure it to your needs.

**Comment by lstauber** [comment]
I'm sorry, I don't know, how to use KeyboardNavigation to stop such behavior… KeyboardNavigation.SetDirectionalNavigation(????, ????) ?
Do you have an idea?

**Comment by tom-englert** [comment]
@lstauber https://github.com/tom-englert/DataGridExtensions/commit/c7d4177c1642cf355e7ec6929cb88ae4f8a375fc
